---
title: "Tidyverse"
author: "Tommy Weber"

number-sections: true
number-depth: 5
---

## Adding Libraries

```{r}
#| message: false
library(tidyverse)
library(readxl)
library(lubridate)
```

## Importing Files

```{r}
#| message: false
bikes_tbl <- read_excel("../../cm_data/01_raw_data/bikes.xlsx")
bikeshops_tbl <- read_excel("../../cm_data/01_raw_data/bikeshops.xlsx")
orderlines_tbl <- read_excel("../../cm_data/01_raw_data/orderlines.xlsx")
```

## Examining Data

```{r}
glimpse(bikes_tbl)
glimpse(bikeshops_tbl)
glimpse(orderlines_tbl)
```

## Joining Data

```{r}
bike_orderlines_joined_tbl <- orderlines_tbl %>%
  left_join(bikes_tbl, by = join_by('product.id' == 'bike.id')) %>% 
  left_join(bikeshops_tbl, by = join_by('customer.id' == 'bikeshop.id'))
```

## Wrangling Data

```{r}

bike_orderlines_wrangled_tbl <- bike_orderlines_joined_tbl %>% 
  separate(col = location,
           into = c("city", "state"),
           sep = ", ") %>%
  mutate(total_price = price * quantity)
```

## Business Insights
### Sales by States

#### Manipulate
```{r}
sales_by_states_tbl <- bike_orderlines_wrangled_tbl %>%
  select(state, total_price) %>% 
  group_by(state) %>% 
  summarise(sales = sum(total_price)) %>% 
  mutate(sales_text = scales::dollar(sales, big.mark = ".", 
                                     decimal.mark = ",", 
                                     prefix = "", 
                                     suffix = " €"))

sales_by_states_tbl %>% 
  arrange(-sales) %>% 
  head(10)
```

#### Visualize
```{r plot1, fig.width=12, fig.height=8}
#| message: false
sales_by_states_tbl %>%
  
  ggplot(aes(x = state, y = sales)) +
  
  geom_col(fill = "#2DC6D6") +
  geom_label(aes(label = sales_text)) +
  geom_smooth(method = "lm", se = FALSE) +
  
  scale_y_continuous(labels = scales::dollar_format(big.mark = ".", 
                                                    decimal.mark = ",", 
                                                    prefix = "", 
                                                    suffix = " €")) +
  labs(
    title    = "Revenue by year",
    subtitle = "Upward Trend",
    x = "",
    y = "Revenue"
  ) + 
  
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

North Rhine-Westphalia has the highest total revenue.

### Sales by States and Years

#### Manipulate

```{r}
#| message: false
sales_by_states_and_years_tbl <- bike_orderlines_wrangled_tbl %>%
  select(state, order.date, total_price) %>%
  mutate(year = year(order.date)) %>% 
  group_by(state, year) %>% 
  summarise(sales = sum(total_price)) %>%
  ungroup() %>% 
  mutate(sales_text = scales::dollar(sales, big.mark = ".", 
                                     decimal.mark = ",", 
                                     prefix = "", 
                                     suffix = " €"))

sales_by_states_and_years_tbl %>% head(10)
```

#### Visualize

```{r plot2, fig.width=12, fig.height=8}
#| message: false

sales_by_states_and_years_tbl %>% 
  
  ggplot(aes(x = year, y = sales, fill = state)) +
  
  geom_col() +

  facet_wrap(~ state) +
  
  scale_y_continuous(labels = scales::dollar_format(big.mark = ".", 
                                                    decimal.mark = ",", 
                                                    prefix = "", 
                                                    suffix = " €")) +
  labs(
    title = "Revenue by year and main category",
    subtitle = "Each product category has an upward trend",
    fill = "Main category" # Changes the legend name
  )
```









